### ISSUE TITLE
URL for enrichr libraries moved

### ISSUE THREAD

**Issue by pcahan1** [zqfang/GSEApy#110]
Thank you for the excellent tool!

Calling gp.enrichr on a custom geneset results in ...

> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='amp.pharm.mssm.edu', port=80): Max retries exceeded with url: /Enrichr/datasetStatistics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1837d5f40>: Failed to establish a new connection: [Errno 61] Connection refused'))

It looks like the URL needs to be changed. I might suggest switching on local/custom vs remote, and in the former, no need to call get_libraries, or at least have the url be an argument with default set to current url

**Comment by zqfang** [comment]
Now, this bug has been fixed.  Also, we could set to current url mannually

```python
        from gseapy.enrichr import Enrichr
        enr = Enrichr(gene_list=...)
        # set organism
        enr.set_organism()
        enr.ENRICHR_URL = "http://maayanlab.cloud"
        enr.run()
        print(enr.results.head())
```

**Comment by Sa753** [comment]
Hi,

Unfortunately, I am still getting the same error . I have human gene list and took out 'organism' but still having the error?. Could you please advise?

   169         ADDLIST_URL = 'http://amp.pharm.mssm.edu/%s/addList'%self._organism
    170         job_id = self.send_genes(gene_list, ADDLIST_URL)
--> 171         user_list_id = job_id['userListId']
    172 
    173         RESULTS_URL = 'http://amp.pharm.mssm.edu/%s/export'%self._organism

KeyError: 'userListId'

**Comment by zqfang** [comment]
@gouinK , Do you connect to Enrichr server successfully?  I think the enrichr server is updating their service. The URL is kinda unstable.

Here is you could do it mannually:

```python
  from gseapy.enrichr import Enrichr
  enr = Enrichr(gene_list=..., gene_sets= ...) # set your parameters
  # set organism
  enr.set_organism() # set organism and default url

  # print out the enrichr url
  print(enr.ENRICHR_URL) 
  ### "http://maayanlab.cloud"   

  # if the URL not work for you, try "http://amp.pharm.mssm.edu"
  # enr.ENRICHR_URL = "http://amp.pharm.mssm.edu"
  # then query the server 
  enr.run()
  print(enr.results.head())
```

**Comment by gouinK** [comment]
Thanks for your help, even with setting the URL to  "http://amp.pharm.mssm.edu" I still get this error:

SSLError: HTTPSConnectionPool(host='maayanlab.cloud', port=443): Max retries exceeded with url: /Enrichr/datasetStatistics (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1124)')))

**Comment by gouinK** [comment]
I was able to fix this error by adding 'verify=False' to every call to requests.get() and requests.post() in your code.
Not sure how common this error is, but would be easy enough to add this as a parameter in your functions.

**Comment by zqfang** [comment]
Thanks for your feedback. That's really helpful. I'll do it to make the connection more stable

**Comment by zqfang** [comment]
Thanks for your feedback. That's really helpful. I'll do it to make the connection more stable

**Comment by KANG-BIOINFO** [comment]
Thanks for the great tool. I also have the same error, which was only seen in one of my computer when I run the code.

SSLError: HTTPSConnectionPool(host='maayanlab.cloud', port=443): Max retries exceeded with url: /Enrichr/datasetStatistics (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

Here's my code:

gene_list = ["CD3D","CD8A","CD8B"]
enr = gp.enrichr(gene_list=gene_list,
                 gene_sets=['GO_Biological_Process_2021',
                           'GO_Molecular_Function_2021',
                           'GO_Cellular_Component_2021'],
                 organism='Human', # don't forget to set organism to the one you desired! e.g. Yeast
                 description='enrichr',
                 # no_plot=True,
                 cutoff=0.5 # test dataset, use lower value from range(0,1)
                )

**Comment by KANG-BIOINFO** [comment]
Thanks for the great tool. I also have the same error, which was only seen in one of my computer when I run the code.

> SSLError: HTTPSConnectionPool(host='maayanlab.cloud', port=443): Max retries exceeded with url: /Enrichr/datasetStatistics (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

Here's my code:
```python
gene_list = ["CD3D","CD8A","CD8B"]
enr = gp.enrichr(gene_list=gene_list,
                            gene_sets=['GO_Biological_Process_2021',
                            'GO_Molecular_Function_2021',
                            'GO_Cellular_Component_2021'],
                            organism='Human', # don't forget to set organism to the one you desired! e.g. Yeast
                            description='enrichr',
                            # no_plot=True,
                            cutoff=0.5 # test dataset, use lower value from range(0,1)
)
```

**Comment by ioannisa92** [comment]
Hello,

I have the exact same error. Is there a bug fix on the way? 

I also tried the solution proposed by @zqfang but I get the following error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-63-20cedb4997f2> in <module>
      2 enr = Enrichr(gene_sets='MSigDB_Oncogenic_Signatures', gene_list = list(rnk[0].values))
      3 # set organism
----> 4 enr.set_organism()
      5 enr.ENRICHR_URL = "https://maayanlab.cloud/Enrichr/#libraries"
      6 enr.run()

AttributeError: 'Enrichr' object has no attribute 'set_organism'`

**Comment by zqfang** [comment]
@ioannisa92 , you may install the lastest version and try again

**Comment by eschmauch** [comment]
Hi ! I updated the package (I'm running version 0.10.05) but I still get that error: 

`ConnectionError: HTTPConnectionPool(host='maayanlab.cloud', port=80): Max retries exceeded with url: /Enrichr/datasetStatistics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8221aa5b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

It is quite weird as trying the URL maayanlab.cloud/Enrichr/datasetStatistics  works in a browser. 

Thanks !
