### ISSUE TITLE
Failing with 1.1.5 - empty gene list not excluded

### ISSUE THREAD

**Issue by enryH** [zqfang/GSEApy#303]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import gseapy; print(gseapy.__version__)
```
1.1.5

### Expected behaviour

- return results

### Actual behaviour

somehow the gene list is empty and then a devision by zero happend. It was introduced with 1.1.5, 1.1.4 does still work.

### Steps to reproduce
```python
[/usr/local/lib/python3.11/dist-packages/gseapy/__init__.py](https://localhost:8080/#) in ssgsea(data, gene_sets, outdir, sample_norm_method, correl_norm_type, min_size, max_size, permutation_num, weight, ascending, threads, figsize, format, graph_num, no_plot, seed, verbose, *args, **kwargs)
    289         verbose=verbose,
    290     )
--> 291     ss.run()
    292     return ss
    293 

[/usr/local/lib/python3.11/dist-packages/gseapy/ssgsea.py](https://localhost:8080/#) in run(self)
    129         # filtering out gene sets and build gene sets dictionary
    130         self._gene_isupper = self.check_uppercase(gene_list=normdat.index.values)
--> 131         gmt = self.load_gmt(gene_list=normdat.index.values, gmt=self.gene_sets)
    132         self.gmt = gmt
    133         self._logger.info(

[/usr/local/lib/python3.11/dist-packages/gseapy/base.py](https://localhost:8080/#) in load_gmt(self, gene_list, gmt)
    332         ups = []
    333         for s in subsets[:20]:
--> 334             ups.append(self.check_uppercase(genesets_dict[s]))
    335 
    336         if (not self._gene_isupper) and all(ups):

[/usr/local/lib/python3.11/dist-packages/gseapy/base.py](https://localhost:8080/#) in check_uppercase(self, gene_list)
    255         """
    256         is_upper = [s.isupper() for s in gene_list]
--> 257         if sum(is_upper) / len(is_upper) >= 0.9:
    258             return True
    259         return False

ZeroDivisionError: division by zero
```

you can run this notebook until the error. [link](https://colab.research.google.com/github/Multiomics-Analytics-Group/acore/blob/main/docs/api_examples/enrichment_analysis.ipynb#scrollTo=e211bf65)

**Comment by zqfang** [comment]
good catch.  the v1.1.5 start to try to convert gene symbols to uppercase if not matched with GMT input. now is fixed

**Comment by enryH** [comment]
thanks. And great you keep the library alive. But then it will still throw an `ValueError`. So how is it possible to run into that issue? Or do you catch the ValueError upstream?

**Comment by zqfang** [comment]
Yes. can you show me the  error mesasge?

**Comment by pcahan1** [comment]
prerank in v1.1.5 throws an error related to this issue (I think) but rolling back to v1.1.4 fixes it:

> gp.prerank(
              ^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scn3/lib/python3.12/site-packages/gseapy/__init__.py", line 396, in prerank
    pre.run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scn3/lib/python3.12/site-packages/gseapy/gsea.py", line 559, in run
    self._gene_isupper = self.check_uppercase(gene_list=dat2.index.values)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/scn3/lib/python3.12/site-packages/gseapy/base.py", line 256, in check_uppercase
    is_upper = [s.isupper() for s in gene_list]
                ^^^^^^^^^
AttributeError: 'numpy.int64' object has no attribute 'isupper'

**Comment by zqfang** [comment]
I'll relase a new bug fix version soon to re-solved this. Thanks

**Comment by zqfang** [comment]
the issue fixed in v1.1.7.
